name: Deploy GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sh deploy-to-github-page.sh

      - name: Commit files
        run: |
          git config --local user.email "guts.inaq@gmail.com"
          git config --local user.name "omricer"
          git add .
          git commit -m "Deploy GitHub Pages" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
